### ISSUE TITLE
Consider using the `cpufeatures` crate

### ISSUE THREAD

**Issue by str4d** [pornin/rust-fn-dsa#3]
Every call to `has_avx2` performs a runtime check:
https://github.com/pornin/rust-fn-dsa/blob/8d01465a47c804296ad5bd248d8f3912231c3d60/fn-dsa-comm/src/lib.rs#L229-L260

The `cpufeatures` crate provides an equivalent `no_std`-compatible alternative to `is_x86_feature_detected!`, that comes with built-in caching (in an `AtomicU8`), and elimination of the runtime checks if AVX2 is enabled at compile time:
```rust
cpufeatures::new!(cpuid_avx2, "avx2");

pub fn has_avx2() -> bool {
    cpuid_avx2::get()
}
```
(or just use the macro-created module / its `InitToken` directly).

**Comment by pornin** [comment]
Well I added that: https://github.com/pornin/rust-fn-dsa/commit/dc0ee5295f80864e9699dff90624d6d48b1f7d91
I am not entirely sure what it brings in practice in this case (apart from an extra dependency), since I was already using the test only in top-level functions (so the cost was negligible). But it seems harmless enough.

**Comment by pornin** [comment]
I guess I'll update that when (if) [RFC 2725](https://github.com/rust-lang/rfcs/pull/2725) is stabilized.
